#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
K8S_DIR="$REPO_ROOT/k8s"
TEMPLATE="$K8S_DIR/secrets.template.yaml"
SECRETS_OUT="$K8S_DIR/secrets.generated.yaml"
PUBKEY_OUT="$K8S_DIR/jwt-public-config.generated.yaml"
SEALED_OUT="$K8S_DIR/sealed-secrets.yaml"

FORCE=0
SEAL=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    --seal) SEAL=1 ;;
    -h|--help) sed -n '2,20p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; exit 2 ;;
  esac
done

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }
[[ -f "$TEMPLATE" ]] || { echo "missing template: $TEMPLATE" >&2; exit 1; }

if [[ -e "$SECRETS_OUT" && $FORCE -eq 0 ]]; then
  echo "refusing to overwrite $SECRETS_OUT (pass --force to rotate every credential)" >&2
  exit 1
fi

# Everything this script writes — including the temp keypair — is owner-only.
umask 077
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

# hex only: safe to interpolate into a connection string and into the sed script below
gen_pw() { openssl rand -hex 24; }
gen_key() { openssl rand -base64 32 | tr -d '\n'; }

openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out "$WORK_DIR/jwt-private.pem" 2>/dev/null
openssl rsa -in "$WORK_DIR/jwt-private.pem" -pubout -out "$WORK_DIR/jwt-public.pem" 2>/dev/null
JWT_PRIVATE_KEY_BASE64="$(base64 < "$WORK_DIR/jwt-private.pem" | tr -d '\n')"
JWT_PUBLIC_KEY_BASE64="$(base64 < "$WORK_DIR/jwt-public.pem" | tr -d '\n')"

# Secrets shared with an external party cannot be invented here; default to empty and warn.
STRIPE_SECRET_KEY="${STRIPE_SECRET_KEY-}"
EMAIL_SMTP_USERNAME="${EMAIL_SMTP_USERNAME-}"
EMAIL_SMTP_PASSWORD="${EMAIL_SMTP_PASSWORD-}"
# Accounting pages its own finance channel on ledger drift. Off unless a bot is supplied.
ACCOUNTING_TELEGRAM_BOT_TOKEN="${ACCOUNTING_TELEGRAM_BOT_TOKEN-}"
ACCOUNTING_TELEGRAM_CHAT_ID="${ACCOUNTING_TELEGRAM_CHAT_ID-}"
if [ -n "$ACCOUNTING_TELEGRAM_BOT_TOKEN" ] && [ -n "$ACCOUNTING_TELEGRAM_CHAT_ID" ]; then
  ACCOUNTING_TELEGRAM_ENABLED="true"
else
  ACCOUNTING_TELEGRAM_ENABLED="false"
fi
# These are HMAC shared secrets: a fresh random value is correct as long as it is copied
# to the peer. Override via env to adopt a value the peer already holds.
STRIPE_WEBHOOK_SECRET="${STRIPE_WEBHOOK_SECRET:-$(gen_key)}"
SHIPPING_API_KEY="${SHIPPING_API_KEY:-$(gen_key)}"
DPD_WEBHOOK_SECRET="${DPD_WEBHOOK_SECRET:-$(gen_key)}"
PPL_WEBHOOK_SECRET="${PPL_WEBHOOK_SECRET:-$(gen_key)}"

cat > "$WORK_DIR/render.sed" <<EOF
s|\\\${AUTH_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${USER_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${INVENTORY_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${PRODUCT_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${PAYMENT_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${ACCOUNTING_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${EMAIL_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${ORDER_WRITE_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${ORDER_READ_POSTGRES_PASSWORD}|$(gen_pw)|g
s|\\\${OPS_CONSOLE_INTERNAL_API_KEY}|$(gen_key)|g
s|\\\${OPS_CONSOLE_ADMIN_API_KEY}|$(gen_key)|g
s|\\\${ORDER_CALLBACK_SHARED_SECRET}|$(gen_key)|g
s|\\\${ORDER_ACCOUNTING_API_KEY}|$(gen_key)|g
s|\\\${JWT_PRIVATE_KEY_BASE64}|${JWT_PRIVATE_KEY_BASE64}|g
s|\\\${STRIPE_SECRET_KEY}|${STRIPE_SECRET_KEY}|g
s|\\\${STRIPE_WEBHOOK_SECRET}|${STRIPE_WEBHOOK_SECRET}|g
s|\\\${SHIPPING_API_KEY}|${SHIPPING_API_KEY}|g
s|\\\${DPD_WEBHOOK_SECRET}|${DPD_WEBHOOK_SECRET}|g
s|\\\${PPL_WEBHOOK_SECRET}|${PPL_WEBHOOK_SECRET}|g
s|\\\${EMAIL_SMTP_USERNAME}|${EMAIL_SMTP_USERNAME}|g
s|\\\${EMAIL_SMTP_PASSWORD}|${EMAIL_SMTP_PASSWORD}|g
s|\\\${ACCOUNTING_TELEGRAM_ENABLED}|${ACCOUNTING_TELEGRAM_ENABLED}|g
s|\\\${ACCOUNTING_TELEGRAM_BOT_TOKEN}|${ACCOUNTING_TELEGRAM_BOT_TOKEN}|g
s|\\\${ACCOUNTING_TELEGRAM_CHAT_ID}|${ACCOUNTING_TELEGRAM_CHAT_ID}|g
EOF

sed -f "$WORK_DIR/render.sed" "$TEMPLATE" > "$SECRETS_OUT"
chmod 600 "$SECRETS_OUT"

if grep -q '\${' "$SECRETS_OUT"; then
  echo "unsubstituted placeholder(s) left in $SECRETS_OUT:" >&2
  grep -o '\${[A-Z_]*}' "$SECRETS_OUT" | sort -u >&2
  rm -f "$SECRETS_OUT"
  exit 1
fi

cat > "$PUBKEY_OUT" <<EOF
# GENERATED by scripts/generate-k8s-secrets.sh — do not edit, do not commit.
# RS256 PUBLIC key matching the private half in secrets.generated.yaml. Not secret, but it
# is regenerated with the keypair, so it stays out of git to guarantee the two never drift.
apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-public-config
  namespace: free-ebay
data:
  Jwt__PublicKeyBase64: "${JWT_PUBLIC_KEY_BASE64}"
EOF
chmod 600 "$PUBKEY_OUT"

if [[ $SEAL -eq 1 ]]; then
  command -v kubeseal >/dev/null || { echo "--seal needs kubeseal on PATH" >&2; exit 1; }
  kubeseal --format yaml < "$SECRETS_OUT" > "$SEALED_OUT"
  echo "sealed -> ${SEALED_OUT#"$REPO_ROOT"/} (safe to commit)"
fi

FINGERPRINT="$(openssl rsa -pubin -in "$WORK_DIR/jwt-public.pem" -outform DER 2>/dev/null | openssl dgst -sha256 | awk '{print $NF}')"

echo "wrote ${SECRETS_OUT#"$REPO_ROOT"/} and ${PUBKEY_OUT#"$REPO_ROOT"/} (mode 0600, gitignored)"
echo "new RS256 public key SHA-256: ${FINGERPRINT}"
[[ -n "$STRIPE_SECRET_KEY" ]] || echo "warning: Stripe__SecretKey is empty — only valid while Stripe__ProviderType=Fake"
[[ -n "$EMAIL_SMTP_PASSWORD" ]] || echo "warning: Email__Password is empty — only valid against in-cluster MailHog"
echo "reminder: copy the carrier/Stripe webhook secrets to the peer, then run kubectl apply -k k8s/"
